update doc
openconfig/grpctunnel pull request #37
Opened 2021-08-12 13:56 UTC by jxx-gg

* added "tunnel" prefix to various places
* added a link in the index.md to the gNMI usage doc
* removed "ack" from the diagram and the doc
* add a description regarding local and tunnel connections at the same time
* removed the description for "capability".

2021-08-12 15:22 UTC, gcsl requested changes

2021-08-12 16:24 UTC, jxx-gg commented on doc/grpctunnel_design.md
> +The `data` field is used to encapsulate raw bytes received from the tunnel client code.
Done

2021-08-12 16:24 UTC, jxx-gg commented on doc/grpctunnel_design.md
> +an ack to the tunnel client. The tunnel client will then check if it can handle the
Done

2021-08-12 16:25 UTC, jxx-gg commented on doc/grpctunnel_design.md
> +session ack back to the tunnel client and the tunnel client will start a new tunnel stream,
Done

2021-08-13 14:36 UTC, jxx-gg commented
just merged to recent update

2021-09-10 13:32 UTC, gcsl approved these changes

2021-09-10 13:35 UTC, merged